sudo: required
notifications:
  email: false
language: java
jdk:
- oraclejdk8
os:
- linux
services:
- docker
env:
- RAPID_FULL="ozlerhakan/rapid:1.26"
script: mvn install
before_install:
- docker run --rm -v /home/travis/build/ozlerhakan/rapid:/rapid -w /rapid/react node npm install
- docker run --rm -v /home/travis/build/ozlerhakan/rapid:/rapid -w /rapid/react node npm run build:prod
- rm -r react/node_modules
- mvn clean
after_success:
- mvn clean
- docker build -t $RAPID_FULL .
- docker tag $RAPID_FULL ozlerhakan/rapid:latest;
- docker images
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push $RAPID_FULL;
  docker push ozlerhakan/rapid:latest;
  fi
