sudo: required
notifications:
  email: false
language: java
node_js:
- node
jdk:
- oraclejdk8
os:
- linux
env:
- RAPID_FULL="ozlerhakan/rapid:1.26"
script: docker run --rm -v ~/.m2:/root/.m2 -v $(PWD):/rapid -w /rapid -v /var/run/docker.sock:/var/run/docker.sock maven:3-jdk-8 mvn clean test
before_install:
- group $USER
- cat /etc/group
- sudo apt-get update
- sudo wget -qO- https://get.docker.com/ | sh
- usermod -aG docker ${USER}
- cat /etc/group
- sudo service docker status
- sudo service docker start
- docker version
- docker pull ubuntu:latest
- docker pull busybox:1.26
- cd react/
- npm install
- npm run build:prod
- cd ..
after_success:
- mvn clean
- docker build -t $RAPID_FULL .
- docker tag $RAPID_FULL ozlerhakan/rapid:latest;
- docker images
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push $RAPID_FULL;
  docker push ozlerhakan/rapid:latest;
  fi
